const errorMessage = {
  missingFields: { errorMessage: 'Missing required fields.' },
  registerUser: { errorMessage: 'The user could not be created.' },
  invalidUser: { errorMessage: 'Invalid user.' },
  duplicateEmail: { errorMessage: 'This email has already been taken.' },
  missingCredentials: { errorMessage: 'Missing email or password.' },
  invalidCredentials: { errorMessage: 'Invalid credentials.' },
  loginUnsuccessful: { errorMessage: 'Login Unsuccessful.' },
  failedDuplicateCheck: { errorMessage: 'There was an error while checking for duplicates.' },
  usersNotRetrieved: { errorMessage: 'The users could not be retrieved.' },
  userNotRetrieved: { errorMessage: 'The user information could not be retrieved.' },
  userNotFound: { errorMessage: 'The user with the specified ID does not exist.' },
  userNotRemoved: { errorMessage: 'The user could not be removed.' },
  userNotUpdated: { errorMessage: 'The user information could not be modified.' },
  eventsNotFound: { errorMessage: 'The user with the specified ID does not have any events.' },
  eventsNotRetrieved: { errorMessage: 'The user events could not be retrieved.' },
  eventNotFound: { errorMessage: 'The event with the specified ID does not exist.' },
  eventNotRetrieved: { errorMessage: 'The event information could not be retrieved.' },
  missingEventInfo: { errorMessage: 'Please provide information for the event.' },
  eventNotAdded: { errorMessage: 'There was an error while saving the post to the database.' },
  eventNotDeleted: { errorMessage: 'The event could not be removed' },
  eventNotUpdated: { errorMessage: 'The event information could not be modified' },
  tasksNotFound: { errorMessage: 'The event with the specified ID does not have any tasks.' },
  tasksNotRetrieved: { errorMessage: 'The tasks information could not be retrieved.' },
  taskNotFound: { errorMessage: 'The task with the specified ID does not exist.' },
  taskNotRetrieved: { errorMessage: 'The task information could not be retrieved.' },
  taskNotRemoved: { errorMessage: 'The task could not be removed.' },
  taskNotUpdated: { errorMessage: 'The task could not be updated.' },
  shoppingListNotFound: { errorMessage: 'The shopping list could not be found.' },
  shoppingListNotRetrieved: { errorMessage: 'The task could not be retrieved.' },
  itemNotFound: { errorMessage: 'The item could not be found.' },
  itemNotRetrieved: { errorMessage: 'The item could not be retrieved.' },
  missingItemInfo: { errorMessage: 'Missing required information.' },
  itemNotCreated: { errorMessage: 'The item could not be created.' },
  itemNotRemoved: { errorMessage: 'The item could not be removed' },
  itemNotUpdated: { errorMessage: 'The item could not be updated.' },
  vendorsNotFound: { errorMessage: 'The vendor could not be found.' },
  vendorsNotRetrieved: { errorMessage: 'The vendors information could not be retrieved.' },
  vendorNotFound: { errorMessage: 'The vendor could not be found.' },
  vendorNotRetrieved: { errorMessage: 'The vendor information could not be retrieved.' },
  missingVendorInfo: { errorMessage: 'Missing required information.' },
  vendorNotCreated: { errorMessage: 'The vendor could not be created.' },
  vendorNotRemoved: { errorMessage: 'The vendor could not be removed.' },
  vendorNotUpdated: { errorMessage: 'The vendor could not be updated.' },
};

module.exports = errorMessage;
